version: "3"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile

# Timescal Database
  timescaledb:
    image: timescale/timescaledb:1.2.1-pg11
    ports:
    - "5432:5432"
    #command: postgres -c 'max_connections=200'
    environment:
       POSTGRES_DB: test
       POSTGRES_USER: maropost
       POSTGRES_PASSWORD: Maro123!
    networks:
      - default
    volumes:
      - /dev/shm:/dev/shm

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    # volumes:
    #   - ./tmp/db/cassandra:/var/lib/cassendra
    networks:
      - default
    volumes:
      - /dev/shm:/dev/shm

  scylladb:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - ./tmp/db/scylladb:/var/lib/scylladb
    networks:
      - default
    volumes:
      - /dev/shm:/dev/shm

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - default
    # volumes:
    #   - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: "test"
      INFLUXDB_USER: "test"
      INFLUXDB_USER_PASSWORD: "test"


  test_cassandra:
    build:
      context: .
      dockerfile: test.dockerfile
    tty: true
    container_name: test
    links:
      - cassandra
    networks:
      - default

  test_scylladb:
    build:
      context: .
      dockerfile: test.dockerfile
    tty: true
    container_name: test
    links:
      - scylladb
    networks:
      - default

  test_timescaledb:
    build:
      context: .
      dockerfile: test.dockerfile
    tty: true
    container_name: test
    links:
      - timescaledb
    networks:
      - default

networks:
  default:
    driver: bridge
