version: "3"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile

# Timescal Database
  timescaledb:
    image: timescale/timescaledb:1.2.1-pg11
    ports:
    - "5432:5432"
    # volumes:
    # - ./tmp/db/timescale:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: test
       POSTGRES_USER: maropost
       POSTGRES_PASSWORD: Maro123!
    networks:
      - default

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./tmp/db/cassandra:/var/lib/cassendra
    networks:
      - default
    volumes:
      - /dev/shm:/dev/shm

  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - ./tmp/db/scylladb:/var/lib/scylladb
    networks:
      - default

  test_cassandra:
    build:
      context: .
      dockerfile: test.dockerfile
    tty: true
    container_name: test
    links:
      - cassandra
    networks:
      - default

  test_scylladb:
    build:
      context: .
      dockerfile: test.dockerfile
    tty: true
    container_name: test
    links:
      - scylla
    networks:
      - default

  test_timescaledb:
    build:
      context: .
      dockerfile: test.dockerfile
    tty: true
    container_name: test
    links:
      - timescaledb
    networks:
      - default

networks:
  default:
    driver: bridge
